'use client';

import React, { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    nav_home: "Accueil",
    nav_browse: "Parcourir",
    nav_sell: "Proposer",
    nav_messages: "Messages",
    hero_title: "Échangez vos Manuels Scolaires",
    hero_subtitle: "La plateforme simple pour échanger vos livres scolaires gratuitement",
    btn_browse: "Parcourir les Livres",
    btn_sell: "Proposer des Livres",
    why_title: "Pourquoi utiliser ReBook ?",
    feature1_title: "Gratuit",
    feature1_desc: "Échangez vos livres gratuitement sans dépenser d'argent. Trouvez exactement ce dont vous avez besoin.",
    feature2_title: "Écologique",
    feature2_desc: "Donnez une seconde vie aux manuels scolaires et réduisez le gaspillage.",
    feature3_title: "Simple",
    feature3_desc: "Interface intuitive pour proposer vos livres et trouver des partenaires d'échange.",
    browse_title: "Parcourir les Manuels",
    filter_subject: "Matière",
    filter_level: "Niveau",
    filter_condition: "État",
    filter_max_price: "Prix max (DH)",
    filter_all: "Toutes",
    subject_math: "Mathématiques",
    subject_physics: "Physique",
    subject_french: "Français",
    subject_english: "Anglais",
    subject_history: "Histoire",
    level_college: "Collège",
    level_lycee: "Lycée",
    condition_excellent: "Excellent",
    condition_good: "Bon",
    condition_fair: "Correct",
    sell_title: "Proposer des Livres",
    form_title: "Titre du livre",
    form_subject: "Matière",
    form_level: "Niveau",
    form_condition: "État",
    form_price: "Prix (DH)",
    form_description: "Description",
    form_contact: "Contact (email ou téléphone)",
    form_payment_type: "Type de paiement",
    payment_cash: "💵 Cash (DH)",
    payment_bc: "💰 Book Coins (BC)",
    btn_publish: "Publier l'annonce",
    success_message: "Votre annonce a été publiée avec succès !",
    btn_request_swap: "🔄 Proposer un Échange",
    swap_title: "Proposer un Échange",
    swap_desc: "Sélectionnez les livres que vous proposez en échange",
    no_books_offered: "Vous n'avez pas encore proposé de livres.",
    btn_initiate_swap: "Proposer l'Échange",
    swap_success: "Votre proposition d'échange a été envoyée !",
    bc_balance: "Solde BC",
    bc_currency: "BC",
    dh: "DH",
    seller: "Vendeur",
    contact: "Contact",
    description: "Description",
    btn_back: "← Retour",
    btn_report: "🚩 Signaler cette annonce",
    report_title: "Signaler cette annonce",
    btn_buy_cash: "Acheter pour",
    btn_buy_bc: "Acheter pour",
    insufficient_bc: "Solde BC insuffisant !",
    payment_type_cash: "💵 Espèces",
    payment_type_bc: "💰 Book Coins",
    ticket_title: "Ticket d'Achat",
    ticket_book: "Livre",
    ticket_price: "Prix",
    ticket_payment: "Paiement",
    ticket_seller: "Vendeur",
    ticket_code: "Code de Transaction",
    ticket_footer: "Présentez ce code au vendeur pour finaliser l'achat",
    ticket_close: "Fermer",
    messages_title: "Mes Messages",
    conversations_title: "Conversations",
    chat_empty: "Sélectionnez une conversation pour commencer",
    chat_input_placeholder: "Tapez votre message...",
    btn_send: "Envoyer",
    btn_contact_seller: "💬 Contacter le vendeur",
    profile_title: "Mon Profil",
    theme_shop: "🎨 Boutique de Thèmes",
  },
  en: {
    nav_home: "Home",
    nav_browse: "Browse",
    nav_sell: "Offer",
    nav_messages: "Messages",
    hero_title: "Swap Your School Textbooks",
    hero_subtitle: "The simple platform to exchange your school books for free",
    btn_browse: "Browse Books",
    btn_sell: "Offer Books",
    why_title: "Why use ReBook?",
    feature1_title: "Free",
    feature1_desc: "Swap your books for free with no money involved. Find exactly what you need.",
    feature2_title: "Ecological",
    feature2_desc: "Give textbooks a second life and reduce waste.",
    feature3_title: "Simple",
    feature3_desc: "Intuitive interface to offer your books and find swap partners.",
    browse_title: "Browse Textbooks",
    filter_subject: "Subject",
    filter_level: "Level",
    filter_condition: "Condition",
    filter_max_price: "Max price (DH)",
    filter_all: "All",
    subject_math: "Mathematics",
    subject_physics: "Physics",
    subject_french: "French",
    subject_english: "English",
    subject_history: "History",
    level_college: "Middle School",
    level_lycee: "High School",
    condition_excellent: "Excellent",
    condition_good: "Good",
    condition_fair: "Fair",
    sell_title: "Offer Books",
    form_title: "Book title",
    form_subject: "Subject",
    form_level: "Level",
    form_condition: "Condition",
    form_price: "Price (DH)",
    form_description: "Description",
    form_contact: "Contact (email or phone)",
    form_payment_type: "Payment type",
    payment_cash: "💵 Cash (DH)",
    payment_bc: "💰 Book Coins (BC)",
    btn_publish: "Publish Ad",
    success_message: "Your ad has been published successfully!",
    btn_request_swap: "🔄 Request Swap",
    swap_title: "Propose a Swap",
    swap_desc: "Select the books you're offering in exchange",
    no_books_offered: "You haven't offered any books yet.",
    btn_initiate_swap: "Propose Swap",
    swap_success: "Your swap request has been sent!",
    bc_balance: "BC Balance",
    bc_currency: "BC",
    dh: "DH",
    seller: "Seller",
    contact: "Contact",
    description: "Description",
    btn_back: "← Back",
    btn_report: "🚩 Report this ad",
    report_title: "Report this ad",
    btn_buy_cash: "Buy for",
    btn_buy_bc: "Buy for",
    insufficient_bc: "Insufficient BC balance!",
    payment_type_cash: "💵 Cash",
    payment_type_bc: "💰 Book Coins",
    ticket_title: "Purchase Ticket",
    ticket_book: "Book",
    ticket_price: "Price",
    ticket_payment: "Payment",
    ticket_seller: "Seller",
    ticket_code: "Transaction Code",
    ticket_footer: "Present this code to the seller to finalize the purchase",
    ticket_close: "Close",
    messages_title: "My Messages",
    conversations_title: "Conversations",
    chat_empty: "Select a conversation to start",
    chat_input_placeholder: "Type your message...",
    btn_send: "Send",
    btn_contact_seller: "💬 Contact Seller",
    profile_title: "My Profile",
    theme_shop: "🎨 Theme Shop",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_browse: "تصفح",
    nav_sell: "اقتراح",
    nav_messages: "الرسائل",
    hero_title: "تبادل كتبك المدرسية",
    hero_subtitle: "المنصة البسيطة لتبادل كتبك المدرسية مجانًا",
    btn_browse: "تصفح الكتب",
    btn_sell: "اقترح كتبًا",
    why_title: "لماذا تستخدم ReBook؟",
    feature1_title: "مجاني",
    feature1_desc: "تبادل كتبك مجانًا بدون أموال. ابحث عما تحتاجه بالضبط.",
    feature2_title: "بيئي",
    feature2_desc: "امنح الكتب المدرسية حياة ثانية وقلل من الهدر.",
    feature3_title: "بسيط",
    feature3_desc: "واجهة بديهية لاقتراح كتبك والعثور على شركاء التبادل.",
    browse_title: "تصفح الكتب المدرسية",
    filter_subject: "المادة",
    filter_level: "المستوى",
    filter_condition: "الحالة",
    filter_max_price: "السعر الأقصى (درهم)",
    filter_all: "الكل",
    subject_math: "الرياضيات",
    subject_physics: "الفيزياء",
    subject_french: "الفرنسية",
    subject_english: "الإنجليزية",
    subject_history: "التاريخ",
    level_college: "الإعدادي",
    level_lycee: "الثانوي",
    condition_excellent: "ممتاز",
    condition_good: "جيد",
    condition_fair: "مقبول",
    sell_title: "اقتراح كتب",
    form_title: "عنوان الكتاب",
    form_subject: "المادة",
    form_level: "المستوى",
    form_condition: "الحالة",
    form_price: "السعر (درهم)",
    form_description: "الوصف",
    form_contact: "الاتصال (البريد الإلكتروني أو الهاتف)",
    form_payment_type: "نوع الدفع",
    payment_cash: "💵 نقدًا (درهم)",
    payment_bc: "💰 عملات الكتب (BC)",
    btn_publish: "نشر الإعلان",
    success_message: "تم نشر إعلانك بنجاح!",
    btn_request_swap: "🔄 اقترح تبادلاً",
    swap_title: "اقتراح تبادل",
    swap_desc: "اختر الكتب التي تقترحها في المقابل",
    no_books_offered: "لم تقترح أي كتب حتى الآن.",
    btn_initiate_swap: "اقترح التبادل",
    swap_success: "تم إرسال طلب التبادل الخاص بك!",
    bc_balance: "رصيد BC",
    bc_currency: "BC",
    dh: "درهم",
    seller: "البائع",
    contact: "الاتصال",
    description: "الوصف",
    btn_back: "رجوع ←",
    btn_report: "🚩 الإبلاغ عن هذا الإعلان",
    report_title: "الإبلاغ عن هذا الإعلان",
    btn_buy_cash: "شراء مقابل",
    btn_buy_bc: "شراء مقابل",
    insufficient_bc: "رصيد BC غير كافٍ!",
    payment_type_cash: "💵 نقدًا",
    payment_type_bc: "💰 عملات الكتب",
    ticket_title: "تذكرة الشراء",
    ticket_book: "الكتاب",
    ticket_price: "السعر",
    ticket_payment: "الدفع",
    ticket_seller: "البائع",
    ticket_code: "كود المعاملة",
    ticket_footer: "قدم هذا الكود للبائع لإتمام عملية الشراء",
    ticket_close: "إغلاق",
    messages_title: "رسائلي",
    conversations_title: "المحادثات",
    chat_empty: "اختر محادثة للبدء",
    chat_input_placeholder: "اكتب رسالتك...",
    btn_send: "إرسال",
    btn_contact_seller: "💬 اتصل بالبائع",
    profile_title: "ملفي الشخصي",
    theme_shop: "🎨 متجر الثيمات",
  }
};

type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
